'use strict';

import { StatCard } from './components/stat-card.js';
import { FormInput } from './components/form-input.js';
import { FormTextarea } from './components/form-textarea.js';
import { SelectDropdown } from './components/select-dropdown.js';
import { ButtonPrimary } from './components/button-primary.js';
import { ButtonAction } from './components/button-action.js';
import { ToastContainer } from './components/toast-container.js';
import { ModalDialog } from './components/modal-dialog.js';
import { CalendarGrid } from './components/calendar-grid.js';
import { NavMenuItem } from './components/nav-menu-item.js';
import { TitleBar } from './components/title-bar.js';
import { ToolTip } from './components/tool-tip.js';
import { ReportBuilder } from './components/report-builder.js';
import { ActivitySelector } from './components/activity-selector.js';

customElements.define('title-bar', TitleBar);
customElements.define('tool-tip', ToolTip);
customElements.define('stat-card', StatCard);
customElements.define('form-input', FormInput);
customElements.define('form-textarea', FormTextarea);
customElements.define('select-dropdown', SelectDropdown);
customElements.define('button-primary', ButtonPrimary);
customElements.define('button-action', ButtonAction);
customElements.define('toast-container', ToastContainer);
customElements.define('modal-dialog', ModalDialog);
customElements.define('calendar-grid', CalendarGrid);
customElements.define('nav-menu-item', NavMenuItem);
customElements.define('report-builder', ReportBuilder);
customElements.define('activity-selector', ActivitySelector);
